# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instarecom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendrequest',
            name='personality',
            field=models.TextField(default=''),
        ),
    ]
